export type CountryGroupCode = 'DE' | 'AT' | 'EU';
export interface ICountryOption {
    code?: CountryCode;
    displayNameLang: string;
    value?: CountryName;
}

export enum CountryCode {
    Germany = 'DE',
    Austria = 'AT',
    Belgium = 'BE',
    Bulgaria = 'BG',
    Croatia = 'HR',
    Cyprus = 'CY',
    Czech = 'CZ',
    Denmark = 'DK',
    Estonia = 'EE',
    Finland = 'FI',
    France = 'FR',
    Greece = 'GR',
    Hungary = 'HU',
    Ireland = 'IE',
    Italy = 'IT',
    Latvia = 'LV',
    Lithuania = 'LT',
    Luxembourg = 'LU',
    Malta = 'MT',
    Netherlands = 'NL',
    Poland = 'PL',
    Portugal = 'PT',
    Romania = 'RO',
    Slovakia = 'SK',
    Slovenia = 'SI',
    Spain = 'ES',
    Sweden = 'SE',
}

export enum CountryName {
    Germany = 'Germany',
    Austria = 'Austria',
    Belgium = 'Belgium',
    Bulgaria = 'Bulgaria',
    Croatia = 'Croatia',
    Cyprus = 'Cyprus',
    Czech = 'Czech',
    Denmark = 'Denmark',
    Estonia = 'Estonia',
    Finland = 'Finland',
    France = 'France',
    Greece = 'Greece',
    Hungary = 'Hungary',
    Ireland = 'Ireland',
    Italy = 'Italy',
    Latvia = 'Latvia',
    Lithuania = 'Lithuania',
    Luxembourg = 'Luxembourg',
    Malta = 'Malta',
    Netherlands = 'Netherlands',
    Poland = 'Poland',
    Portugal = 'Portugal',
    Romania = 'Romania',
    Slovakia = 'Slovakia',
    Slovenia = 'Slovenia',
    Spain = 'Spain',
    Sweden = 'Sweden',
}

export const countryCodeToNameMap: Record<CountryCode, CountryName> = {
    DE: CountryName.Germany,
    AT: CountryName.Austria,
    BE: CountryName.Belgium,
    BG: CountryName.Bulgaria,
    HR: CountryName.Croatia,
    CY: CountryName.Cyprus,
    CZ: CountryName.Czech,
    DK: CountryName.Denmark,
    EE: CountryName.Estonia,
    FI: CountryName.Finland,
    FR: CountryName.France,
    GR: CountryName.Greece,
    HU: CountryName.Hungary,
    IE: CountryName.Ireland,
    IT: CountryName.Italy,
    LV: CountryName.Latvia,
    LT: CountryName.Lithuania,
    LU: CountryName.Luxembourg,
    MT: CountryName.Malta,
    NL: CountryName.Netherlands,
    PL: CountryName.Poland,
    PT: CountryName.Portugal,
    RO: CountryName.Romania,
    SK: CountryName.Slovakia,
    SI: CountryName.Slovenia,
    ES: CountryName.Spain,
    SE: CountryName.Sweden,
};

export const countryNameToCodeMapEN: Record<string, CountryCode> = {
    Germany: CountryCode.Germany,
    Austria: CountryCode.Austria,
    //
    Belgium: CountryCode.Belgium,
    Bulgaria: CountryCode.Bulgaria,
    Croatia: CountryCode.Croatia,
    Cyprus: CountryCode.Cyprus,
    Czech: CountryCode.Czech,
    Denmark: CountryCode.Denmark,
    Estonia: CountryCode.Estonia,
    Finland: CountryCode.Finland,
    France: CountryCode.France,
    Greece: CountryCode.Greece,
    Hungary: CountryCode.Hungary,
    Ireland: CountryCode.Ireland,
    Italy: CountryCode.Italy,
    Latvia: CountryCode.Latvia,
    Lithuania: CountryCode.Lithuania,
    Luxembourg: CountryCode.Luxembourg,
    Malta: CountryCode.Malta,
    Netherlands: CountryCode.Netherlands,
    Poland: CountryCode.Poland,
    Portugal: CountryCode.Portugal,
    Romania: CountryCode.Romania,
    Slovakia: CountryCode.Slovakia,
    Slovenia: CountryCode.Slovenia,
    Spain: CountryCode.Spain,
    Sweden: CountryCode.Sweden,
};

export const countryNameToCodeMapDE: Record<string, CountryCode> = {
    Deutschland: CountryCode.Germany,
    Österreich: CountryCode.Austria,
    //
    Belgien: CountryCode.Belgium,
    Bulgarien: CountryCode.Bulgaria,
    Kroatien: CountryCode.Croatia,
    Zypern: CountryCode.Cyprus,
    Tschechien: CountryCode.Czech,
    Dänemark: CountryCode.Denmark,
    Estland: CountryCode.Estonia,
    Finnland: CountryCode.Finland,
    Frankreich: CountryCode.France,
    Griechenland: CountryCode.Greece,
    Ungarn: CountryCode.Hungary,
    Irland: CountryCode.Ireland,
    Italien: CountryCode.Italy,
    Lettland: CountryCode.Latvia,
    Litauen: CountryCode.Lithuania,
    Luxemburg: CountryCode.Luxembourg,
    Malta: CountryCode.Malta,
    Niederlande: CountryCode.Netherlands,
    Polen: CountryCode.Poland,
    Portugal: CountryCode.Portugal,
    Rumänien: CountryCode.Romania,
    Slowakei: CountryCode.Slovakia,
    Slowenien: CountryCode.Slovenia,
    Spanien: CountryCode.Spain,
    Schweden: CountryCode.Sweden,
};
// not includes Germany and Austria

export const EU_COUNTRY_KEYS = [
    'country-belgium',
    'country-bulgaria',
    'country-croatia',
    'country-cyprus',
    'country-czech',
    'country-denmark',
    'country-estonia',
    'country-finland',
    'country-france',
    'country-greece',
    'country-hungary',
    'country-ireland',
    'country-italy',
    'country-latvia',
    'country-lithuania',
    'country-luxembourg',
    'country-malta',
    'country-netherlands',
    'country-poland',
    'country-portugal',
    'country-romania',
    'country-slovakia',
    'country-slovenia',
    'country-spain',
    'country-sweden',
];

export const countryTabOptions: ICountryOption[] = [
    {
        code: CountryCode.Germany,
        displayNameLang: 'country-germany',
        value: CountryName.Germany,
    },
    {
        code: CountryCode.Austria,
        displayNameLang: 'country-austria',
        value: CountryName.Austria,
    },
    {
        displayNameLang: 'country-europe',
    },
];

export const countrySelectorOptions: ICountryOption[] = [
    {
        code: CountryCode.Belgium,
        displayNameLang: 'country-belgium',
        value: CountryName.Belgium,
    },
    {
        code: CountryCode.Bulgaria,
        displayNameLang: 'country-bulgaria',
        value: CountryName.Bulgaria,
    },
    {
        code: CountryCode.Croatia,
        displayNameLang: 'country-croatia',
        value: CountryName.Croatia,
    },
    {
        code: CountryCode.Cyprus,
        displayNameLang: 'country-cyprus',
        value: CountryName.Cyprus,
    },
    {
        code: CountryCode.Czech,
        displayNameLang: 'country-czech',
        value: CountryName.Czech,
    },
    {
        code: CountryCode.Denmark,
        displayNameLang: 'country-denmark',
        value: CountryName.Denmark,
    },
    {
        code: CountryCode.Estonia,
        displayNameLang: 'country-estonia',
        value: CountryName.Estonia,
    },
    {
        code: CountryCode.Finland,
        displayNameLang: 'country-finland',
        value: CountryName.Finland,
    },
    {
        code: CountryCode.France,
        displayNameLang: 'country-france',
        value: CountryName.France,
    },
    {
        code: CountryCode.Greece,
        displayNameLang: 'country-greece',
        value: CountryName.Greece,
    },
    {
        code: CountryCode.Hungary,
        displayNameLang: 'country-hungary',
        value: CountryName.Hungary,
    },
    {
        code: CountryCode.Ireland,
        displayNameLang: 'country-ireland',
        value: CountryName.Ireland,
    },
    {
        code: CountryCode.Italy,
        displayNameLang: 'country-italy',
        value: CountryName.Italy,
    },
    {
        code: CountryCode.Latvia,
        displayNameLang: 'country-latvia',
        value: CountryName.Latvia,
    },
    {
        code: CountryCode.Lithuania,
        displayNameLang: 'country-lithuania',
        value: CountryName.Lithuania,
    },
    {
        code: CountryCode.Luxembourg,
        displayNameLang: 'country-luxembourg',
        value: CountryName.Luxembourg,
    },
    {
        code: CountryCode.Malta,
        displayNameLang: 'country-malta',
        value: CountryName.Malta,
    },
    {
        code: CountryCode.Netherlands,
        displayNameLang: 'country-netherlands',
        value: CountryName.Netherlands,
    },
    {
        code: CountryCode.Poland,
        displayNameLang: 'country-poland',
        value: CountryName.Poland,
    },
    {
        code: CountryCode.Portugal,
        displayNameLang: 'country-portugal',
        value: CountryName.Portugal,
    },
    {
        code: CountryCode.Romania,
        displayNameLang: 'country-romania',
        value: CountryName.Romania,
    },
    {
        code: CountryCode.Slovakia,
        displayNameLang: 'country-slovakia',
        value: CountryName.Slovakia,
    },
    {
        code: CountryCode.Slovenia,
        displayNameLang: 'country-slovenia',
        value: CountryName.Slovenia,
    },
    {
        code: CountryCode.Spain,
        displayNameLang: 'country-spain',
        value: CountryName.Spain,
    },
    {
        code: CountryCode.Sweden,
        displayNameLang: 'country-sweden',
        value: CountryName.Sweden,
    },
];
